### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by jlyon** [GovReady/security-stories-nist800-53#4]
@gregelin  what makes the most sense in terms of grouping issues and naming files?  We were thinking for this current pass we would group issues by family.  The names could be something like:

AU_low_impact_pri1.yaml
AC_low_impact_pri1.yaml
...

Does this sound good, or would you like another grouping pattern?

**Comment by gregelin** [comment]
@jlyon Let's keep everything lowercase, otherwise naming schema is fine. Also OK to do:

`au_low_impact_pri1_1.yaml`, `au_low_impact_pri1_2.yaml` if there's a logical reason to break a family up into smaller groups.

**Comment by jlyon** [comment]
Sounds good, thanks.
